DRIVERS_FILES = ps2m.cc
#dummy1.cc -DDRIVER_DUMMY1 
DRIVERS_PATH = kernel/drivers/devs/
DRIVERS_OBJS = $(patsubst %.cc,%.o,$(addprefix $(DRIVERS_PATH),$(DRIVERS_FILES)))
DRIVERS_FLAGS = -DDRIVER_PS2M
FLAGS_CXX = -DEARLY_LOG_ERR -DEARLY_LOG_INFO -DEARLY_LOG_DBG -DPCI_DISABLE_LOG


